/// Flutter icons Iconx
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconx
///      fonts:
///       - asset: fonts/Iconx.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Iconx {
  Iconx._();

  static const _kFontFam = 'Iconx';

  static const IconData facebook_logo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hashtag = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home_icon_silhouette = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData instagram_logo = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData mobile_phone = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData motivational = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData sitemap = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData dots_menu = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData facebook_logo_1 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData instagram_logo_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData social_media_twitter = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData youTube = const IconData(0xe80c, fontFamily: _kFontFam);
}
